version: "3.7"

services:
  webglearth:
    image: php:7.2-apache
    container_name: webglearth
    expose:
      - 80
      - 443
    volumes:
      - ./public:/var/www/html
    restart: always
    environment:
      - VIRTUAL_HOST=$VIRTUAL_HOST
      - LETSENCRYPT_HOST=$LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL=$LETSENCRYPT_EMAIL

networks:
  default:
    external:
      name: nginx-proxy
