services:
  website:
    image: nginx:alpine
    container_name: webglearth
    restart: unless-stopped
    volumes:
      - ./public:/usr/share/nginx/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webglearth.rule=Host(`webglearth.maksimlebedev.ru`)"
      - "traefik.http.routers.webglearth.tls=true"
      - "traefik.http.routers.webglearth.tls.certresolver=letsencrypt"
      - "traefik.http.services.webglearth.loadbalancer.server.port=80"
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
